[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
version_files = ["package.json:\"version\""]
tag_format = "js-v$version"
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
